### ISSUE TITLE
Adding blank patient

### ISSUE THREAD

**Issue by NikhilP99** [bits-his/bits-his#26]
**Describe the bug**
If we cancel adding a new patient, it adds the patient anyways even without entering any data in the fields.

**To Reproduce**
1. Go to Record module
2. Click on Add Patient
3. Click on Cancel
4. See black patient

**Expected behavior**
Should not add a patient.

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser: Firefox
 - Version 76.0.1 (64 bit)

**Comment by emaitee** [comment]
Thanks for raising this, it is being looked into

**Comment by sammiepius** [comment]
i just merged a fix now, you can check it
