### ISSUE TITLE
website link not working

### ISSUE THREAD

**Issue by muhammadui** [bits-his/bits-his#29]
**Live preview of the site is not working**
---
it returns this application error text.

Application error
An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details. You can do this from the Heroku CLI with the command
```bash
heroku logs --tail
```

**Comment by emaitee** [comment]
@muhammadui, the deployment server must've been download, thanks for lettting us know, I belief it is back up now. Thanks for your contribution
