### ISSUE TITLE
Can i know if this is only frontend , i am new to node , however i cannot find backend nodejs server.

### ISSUE THREAD

**Issue by sunilparajuli** [bits-his/bits-his#32]
is this frontend only? i got api call in heroku , i guess its frontend only.

**Comment by emaitee** [comment]
Only the frontend was open-sourced basically because there was no request for the backend server. The team will consider this request and let you know if the backend nodejs server is available. @bits-his/backend-wizards

**Comment by sunilparajuli** [comment]
Thank you for your reply. I intend to add more services to this system (FHIR) system and open-source the project. However since, the backend is a closed system, I need to rebuild the whole system according to the response of the frontend which is not that complex but it kinda takes a lot of effort and time.  Let me know if the team can consider this request.

**Comment by 8790fahad** [comment]
Thanks Mr Sunil Parajuli for reaching out to bit-his team, for now we
don't have a backend for our bits-his frontend but with this request we are
going to provide it, and it will be available on github by the next 48
hours.

Backend Team Lead
Fahad Ado Muhammad

**Comment by sunilparajuli** [comment]
Looking forward to this @8790fahad.

**Comment by 8790fahad** [comment]
Thanks for dropping your mail.

I would connect you with the right person.

Give me sometime.

**Comment by sunilparajuli** [comment]
Sure thank you @8790fahad

**Comment by sunilparajuli** [comment]
@8790fahad  can i know when can i get updates. This application, which i intended to use is with openIMIS as a FHIR implementation which you guys will also get credits for if applicable. While if not possible to share the backend , i need each response json for me to build backend separately.
